<!-- Main content -->
<?php $homeLink = $this->serverUrl($this->basePath()); ?>
<section class="fullscreen">
    <div class="container v-align-transform">
        <div class="row">
            <div class="col-sm-10 col-sm-offset-1">
                <div class="text-center">
                    <i class="ti-receipt icon icon-lg mb24 mb-xs-0"></i>
                    <h1 class="large">404</h1>
                    <p><?php echo $this->translate('Oops, an error has occurred. Page not found!'); ?></p>
                    <a class="btn" href="<?php echo $homeLink; ?>"><?php echo $this->translate('Go to homepage'); ?></a>

                </div>
            </div>
        </div>
        <!--end of row-->

    </div>
    <!--end of container-->
</section>
<!--<div class="page-container" style=" min-height:650px ">
<div class="content-wrapper1 container page404">
    <div class="container-fluid text-center">
        <h1 class="error-title">404</h1>
        <h6 class="text-semibold content-group">Oops, an error has occurred. Page not found!</h6>
        <div class="row">
            <div class="col-lg-4 col-lg-offset-4 col-sm-6 col-sm-offset-3">
                <div class="row">
                    <div class="col-lg-12">
                        <a href="<?php //echo $this->url('users');  ?>" class="btn btn-primary btn-block content-group"><i class="icon-circle-left2 position-left"></i> Go to homepage</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>-->
<!-- /main content -->