<?php
echo $this->doctype();
?>
<html>
    <!-- login layout -->
    <head>
        <meta charset="utf-8"> 
        <?php
        echo $this->headTitle("Welcome");
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
        ?>
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css">
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                ->prependStylesheet($this->basePath('css/components.css?v=' . filemtime(getcwd() . "/public/css/components.css")))
                ->prependStylesheet($this->basePath('css/bootstrap.css?v=' . filemtime(getcwd() . "/public/css/bootstrap.css")))
                ->prependStylesheet($this->basePath('css/theme_admin_panel.css?v=' . filemtime(getcwd() . "/public/css/theme_admin_panel.css")));
        ?>

        <script type="text/javascript" src="<?php echo $this->basePath('js/jquery.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath('js/bootstrap.min.js'); ?>"></script>


        <script type="text/javascript" src="<?php echo $this->basePath('js/pages/form_select2.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath('js/pages/select2.min.js'); ?>"></script>

        <script type="text/javascript">
            // base url
            var basepath = '<?php echo $this->serverUrl($this->basePath()) ?>';
        </script>


        <style type="text/css">
            /*for other*/   
            body.layout-boxed {
                background:#e2e3e3 !important
            }
            .module-center {
                margin-left:0.8% !important;
            }
            @media screen and (max-width:1220px){
                .custom-work .actual-box{
                    text-align:center;
                }
            }

            .card-title {
                font-size: 16px;
                font-weight: 500;
                line-height: 1.2857em;
                max-height: 42px;
                color: #444;
                overflow: hidden;
            }
            .anchor-tag{
                width: 270px;
                height: 360px;
                display:inline-block;
                margin-bottom:11px;
                margin-left:21px;
            }
            .card{
                width:275px;
                height:352px;
                background:#fff;
            }
            .anchor-tag:hover .card {
                box-shadow: 0 14px 28px rgba(0,0,0,0.25), 0 10px 10px rgba(0,0,0,0.22);
                cursor:pointer;
                -webkit-transition: scale 1s;
                transition: scale 1s;
                transform: scale(0.99);
                transition: all 0.4s cubic-bezier(.25,.8,.25,1);
            }
            footer{
                margin-left:0;
            }
            .card-container{
                padding-left:5px;
            }
            @media (max-width:1910px){
                .card-container{
                    text-align:center;
                }
            }

            .filter-search-header {        
                margin-bottom: 20px;            
                height: auto;
                background-repeat: no-repeat;
                background-position: center;
                background-size: cover;
                background-color: #000;
            }
            .card-text {
                clear: both;
                font-size: 13px;
                height: 82px;
                overflow: hidden;
                color: rgba(0, 0, 0, .68);
            }
            .error{
                color: red;
            }
            .modal-custom-section{padding:0px; margin:0px;}
            .modal-custom-section label{padding:0px; margin-bottom:0px;}
            .modal-dialog{margin:100px auto;}
            .modal-custom-section .upload-avatar{padding:0px 30px 0px 30px; margin:0px;}
            .modal-custom-section .input-group{ margin:0px 0px 0px 0px;}
            .modal-custom-section .input-group > input{border:none; border-radius-bottom-right:5px; border-radius-top-right:5px;}
            .modal-custom-section .input-group > input:focus{border:none; box-shadow:none;}
            .modal-custom-section .modal-sm{margin:0px auto; background:#2bb2d2;}
            .modal-custom-section .input-group-addon{background:#fff; border: solid 1px #fff;}
            .modal-custom-section .input-group-addon i{color:#999999;}
            .modal-custom-section button.btn{background:#4d4d4d; color:#fff;}
            .modal-custom-section button.btn:hover{color:#fff;}
            .modal-custom-section p a{color:#fff;}
            .modal-custom-section .modal-footer{padding:0px 0px 20px 0px;}
            .modal-custom-section h4{margin:0px auto; text-align:center; color:#fff;}
            .modal-custom-section .modal-body{padding:0px 20px;}
            .modal-custom-section .close{font-weight:600; color:#fff; opacity:1; font-size:25px;}
            .modal-custom-section .form-group{margin-bottom:15px;}
            .modal-custom-section select.form-control{margin-bottom:0px;}
            .modal-custom-section .form-group > .elem-err,.elem-errr{text-align:right; margin-top:3px;}
        </style>

    </head>
    <body class="layout-boxed">        
        <div class="login-container">            
            <?php echo $this->content; ?>
            <!-- Footer -->
            <?php echo $this->partial('partial/footer.phtml'); ?>
            <!-- /footer -->
        </div>        
    </body>
</html>
