<?php
echo $this->doctype();
?>
<html >
<!-- backend layout-->
    <head>
        <meta charset="utf-8">
        <?php
        $mainTitle = 'Welcome';
        echo $this->headTitle($mainTitle);
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
        ?>
        <!-- Le styles -->
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css">

        <?php        
            $ck_editor_lang_key = 'en';
                echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        //->prependStylesheet($this->basePath('css/other.css?v='.filemtime(getcwd()."/public/css/other.css")))
                        ->prependStylesheet($this->basePath('css/full-container.css?v='.filemtime(getcwd()."/public/css/full-container.css")))
                        ->prependStylesheet($this->basePath('css/footer.css?v='.filemtime(getcwd()."/public/css/footer.css")))                        
                        ->prependStylesheet($this->basePath('css/components.css?v='.filemtime(getcwd()."/public/css/components.css")))
                        ->prependStylesheet($this->basePath('css/core.css?v='.filemtime(getcwd()."/public/css/core.css")))
                        ->prependStylesheet($this->basePath('css/header.css?v='.filemtime(getcwd()."/public/css/header.css")))
                        ->prependStylesheet($this->basePath('css/bootstrap.css?v='.filemtime(getcwd()."/public/css/bootstrap.css")))                       
                        ->prependStylesheet($this->basePath('css/icons/icomoon/styles.css?v='.filemtime(getcwd()."/public/css/icons/icomoon/styles.css")));
        ?>
        <!-- Scripts -->
        <?php
            echo $this->headScript()
				->prependFile($this->basePath('js/bootstrap.min.js?v='.filemtime(getcwd()."/public/js/bootstrap.min.js")))
                ->prependFile($this->basePath('js/jquery.min.js?v='.filemtime(getcwd()."/public/js/jquery.min.js")));        ?>
        <script type="text/javascript">
            // base url
            var basepath = '<?php echo $this->serverUrl($this->basePath()) ?>';           
        </script>
        <style>
		.custom-work .content-wrapper {
			margin-left: unset !important;
		}
		</style>
    </head>    
    <body class="layout-boxed headerbg-change">        
        <div class="page-container">
            <div class="page-content custom-work"> 
                <?php echo $this->content; ?>   
                <?php echo $this->partial('partial/footer.phtml'); ?>
            </div>
        </div>        
    </body>
</html>