<script>
$(window).load(function() {
    $("#session_unicef").hide();
    var unicef_name_cooki = getCookie('unicef_name');
    if(unicef_name_cooki!=''){
        $("#session_unicef").show();
        $("#cooki_name").text(unicef_name_cooki);
    }
});
</script>
<div class="filter-search-header" style="min-height:60px">
    <div id='session_unicef' style="display: block;color: #d2cccc;float: right;padding: 20px 30px;font-size: 20px;">
        Hi, <span id='cooki_name'></span> <span style="cursor: pointer;font-size: 12px;" onclick="removeCookies();">(Not You?)</span>
    </div>
</div>
<div class="page-container">
    <!-- Page content --> 
    <div class="page-content custom-work">
        <!-- Main content -->
        <div class="container">
            <!-- Custom components -->
            <div class="row">
                <div class="col-lg-12 actual-box">
                    <div  style="position:relative" class="anchor-tag">
                        <a href="javascript:void(0)" onclick="checkCookie('ms300035')">
                            <div class="card">
                                <img class="card-img-top" alt="Line and Plane of Symmetry" src="https://s3.amazonaws.com/bucket.veative.com/CONTENTBANK/thumb_MS300035.jpg">
                                <div class="card-block"></div>
                            </div>
                            <div class="card-block-outer">
                                <h4 class="card-title mt-3">Line and Plane of Symmetry</h4>
                                <div class="card-text ">
                                    Symmetry is defined as the quality of having similar parts that match each other in 2-D shapes or figures. A line of symmetry divides a figure into two mirror-image halves.  On the other hand, a plane that divides a 3-D figure into two halves, such that the two halves are mirror images of each other is known as plane of symmetry.
                                </div>

                            </div>
                        </a>
                    </div>
                    <div  style="position:relative" class="anchor-tag">
                        <a href="javascript:void(0)" onclick="checkCookie('ss200049')">
                            <div class="card">
                                <img class="card-img-top" alt="Structure of Phenol" src="https://s3.amazonaws.com/bucket.veative.com/CONTENTBANK/thumb_SS200049.jpg">
                                <div class="card-block"></div>
                            </div>
                            <div class="card-block-outer">
                                <h4 class="card-title mt-3">Structure of Phenol</h4>
                                <div class="card-text ">
                                    In phenol, hydroxy functional group is directly attached to the sp2 hybridized carbon atom of the benzene ring. The interaction of six unhybridized 2pz orbitals of carbon atoms of the benzene ring leads to the formation of delocalized pi-electron clouds.
                                </div>
                                
                            </div>
                        </a>
                    </div>
                    <div  style="position:relative" class="anchor-tag">
                        <a href="javascript:void(0)" onclick="checkCookie('hs300012')">
                            <div class="card">
                                <img class="card-img-top" alt="Introduction to Complex Numbers" src="https://s3.amazonaws.com/bucket.veative.com/CONTENTBANK/thumb_HS300012.jpg">
                                <div class="card-block"></div>
                            </div>
                            <div class="card-block-outer">
                                <h4 class="card-title mt-3">Introduction to Complex Numbers</h4>
                                <div class="card-text ">
                                    A complex number is defined as the combination of real and an imaginary number that can be expressed in the form a + bi, where a and b are real numbers and i is the imaginary unit, satisfying the equation i^2 = −1. In this expression, a is the real part and b is the imaginary part of the complex number.  
                                </div>
                            </div>
                        </a>
                    </div>
                    <div  style="position:relative" class="anchor-tag">
                        <a href="javascript:void(0)" onclick="checkCookie('ms100027')">
                            <div class="card">
                                <img class="card-img-top" alt="Reproductive Parts of a Flower" src="https://s3.amazonaws.com/bucket.veative.com/CONTENTBANK/thumb_MS100027.jpg">
                                <div class="card-block"></div>
                            </div>
                            <div class="card-block-outer">
                                <h4 class="card-title mt-3">Reproductive Parts of a Flower</h4>
                                <div class="card-text ">
                                    Stamens and pistil are the male and female reproductive parts of a flower. Stamen contains anthers and filaments while pistil contains style, stigma and ovary.
                                </div>
                            </div>
                        </a>
                    </div>
                    <div  style="position:relative" class="anchor-tag">
                        <a href="javascript:void(0)" onclick="checkCookie('hs400052')">
                            <div class="card">
                                <img class="card-img-top" alt="Opaque Translucent and Transparent" src="https://s3.amazonaws.com/bucket.veative.com/CONTENTBANK/thumb_HS400052.jpg">
                                <div class="card-block"></div>
                            </div>
                            <div class="card-block-outer">
                                <h4 class="card-title mt-3">Opaque Translucent and Transparent</h4>
                                <div class="card-text ">
                                    Transparent materials transmit light without scattering the waves so that objects are clearly seen through them. Translucent materials transmit light but also scatter light waves so that the objects seen through them appear blurry. Opaque materials absorb and reflect light but do not transmit it, not allowing objects to be seen through them.
                                </div>
                            </div>
                        </a>
                    </div>
                    <div  style="position:relative" class="anchor-tag">
                        <a href="javascript:void(0)" onclick="checkCookie('hs400034')">
                            <div class="card">
                                <img class="card-img-top" alt="Series and Parallel Circuits" src="https://s3.amazonaws.com/bucket.veative.com/CONTENTBANK/thumb_HS400034.jpg">
                                <div class="card-block"></div>
                            </div>
                            <div class="card-block-outer">
                                <h4 class="card-title mt-3">Series and Parallel Circuits</h4>
                                <div class="card-text ">
                                    There are two basic ways in which more than two circuit components can be connected: series and parallel. A series circuit is an electric circuit with only one branch. The amount of current is the same through every part of the circuit. If any part is disconnected, no current runs through the circuit. Parallel circuits contain two or more branches for current. Devices on each branch can be turned on or off separately.
                                </div>
                            </div>
                        </a>
                    </div> 
                </div>
            </div>
            <!-- /custom components -->
        </div>
        <!-- /main content -->
    </div>
    <!-- /page content -->
</div>
<!-- /page container -->
<!-- Basic modal -->
<div id="modal_default" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close model_close" data-dismiss="modal">&times;</button>
                <h5 class="modal-title">Please save your basic details</h5>
            </div>
            <div class="modal-body">                
                    <fieldset class="mb-3">
                        <div class="form-group row">
                            <label class="col-form-label col-lg-2">Full Name</label>
                            <div class="col-lg-10">
                                <input type="text" class="form-control" placeholder="Enter your fullname..." id="username" name="username" maxlength="100">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-form-label col-lg-2">Age</label>
                            <div class="col-lg-10">
                                <input type="text" class="form-control" placeholder="Enter your age..." id="age" name="age" maxlength="3">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-form-label col-lg-2">Gender</label>
                            <div class="col-lg-10">
                                <select class="form-control select" data-fouc id="gender" name="gender">
                                    <option value="Boy">Boy</option>
                                    <option value="Girl">Girl</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-form-label col-lg-2">Avatar</label>
                            <div class="col-lg-10">
                                <select data-placeholder="Select avatar" class="form-control select" data-fouc id="avatar" name="avatar">
                                    <option value="Monkey"  selected> Monkey</option>
                                    <option value="Snake" >Snake</option>
                                    <option value="Zebra" >Zebra</option>
                                    <option value="Flower" >Flower</option>
                                    <option value="Rain" >Rain</option>
                                </select>
                            </div>
                        </div>
                    </fieldset>
                    <div class="text-right">
                        <input type="hidden" id="module_id" name="module_id">
                        <button type="submit" id="submitBtn" class="btn btn-primary">Submit</button>
                    </div>
                
            </div>            
        </div>
    </div>
</div>
<!-- /basic modal -->
 <link href="<?php echo $this->basePath('css/icons/icomoon/styles.css'); ?>" rel="stylesheet" type="text/css">
<script type="text/javascript" charset="UTF-8" src="<?php echo $this->basePath('js/pages/components_modals.js?v='.filemtime(getcwd()."/public/js/pages/components_modals.js")); ?>"></script>
<script>
$(document).ready(function(){
	 
    $(".error").remove();
    var validate = true;
    $("#submitBtn").click(function(){        
        var username = $('#username').val();
        var age = $('#age').val();        
        var gender = $('#gender').val();        
        var avatar = $('#avatar').val();        
        age = parseInt($('#age').val());        
        $(".error").remove();
        
        if (username.length < 1) {
            $('#username').after('<span class="error">Please enter full name.</span>');
            validate = false;
        } else if (age.length < 1) {
            $('#age').after('<span class="error">Please enter age.</span>');
            validate = false;
        } else if(isNaN(age)){
            $('#age').after('<span class="error">Please valid age.</span>');
            validate = false;
        } else if (age < 1) {
            $('#age').after('<span class="error">Please valid age.</span>');
            validate = false;
        } else if (gender.length < 1) {
            $('#gender').after('<span class="error">Please select gender.</span>');
            validate = false;
        } else if (avatar.length < 1) {
            $('#avatar').after('<span class="error">Please select avtar.</span>');
            validate = false;
        }else{
            validate = true;
        }


        //console.log(validate);
        if(validate){
            var date = new Date();
			date.setTime(date.getTime()+(60 * 60 * 24 * 1000 * 1));
			var expires = "; expires="+date.toGMTString();
			
            document.cookie = "unicef_name="+username+expires+";path=/";
            document.cookie = "unicef_age="+age+expires+";path=/";
            document.cookie = "unicef_avatar="+avatar+expires+";path=/";
            document.cookie = "unicef_gender="+gender+expires+";path=/";
            $('#modal_default').find(".model_close").trigger('click');

            //window.location.reload();
            var module_id = $('#module_id').val();
            window.location.href = "http://ec2-52-5-117-32.compute-1.amazonaws.com/WebVR/Aframe/"+module_id;
            
        }
    });

});
function removeCookies(){
    document.cookie = 'unicef_name=; Path=/; Expires=Thu, 01 Jan 1970 00:00:01 GMT;';
    document.cookie = 'unicef_age=; Path=/; Expires=Thu, 01 Jan 1970 00:00:01 GMT;';
    document.cookie = 'unicef_avatar=; Path=/; Expires=Thu, 01 Jan 1970 00:00:01 GMT;';
    document.cookie = 'unicef_gender=; Path=/; Expires=Thu, 01 Jan 1970 00:00:01 GMT;';
    window.location.reload();
}

function getCookie(cname) {
  var name = cname + "=";
  var decodedCookie = decodeURIComponent(document.cookie);
  var ca = decodedCookie.split(';');
  for(var i = 0; i <ca.length; i++) {
    var c = ca[i];
    while (c.charAt(0) == ' ') {
      c = c.substring(1);
    }
    if (c.indexOf(name) == 0) {
      return c.substring(name.length, c.length);
    }
  }
  return "";
}
function checkCookie(moduleId){
    if(getCookie('unicef_name') === ''){
        $("#module_id").val(moduleId);
        $("#modal_default").modal('show');
    }else{
        
        window.location.href = "http://ec2-52-5-117-32.compute-1.amazonaws.com/WebVR/Aframe/"+moduleId;
    }
}


</script>